openapi: 3.0.3
info:
  title: url-service API
  version: 0.1.0
paths:
  /links:
    $ref: "./paths/links.yaml"
  /links/{shortCode}:
    $ref: "./paths/links-shortCode.yaml"
  /links/{shortCode}/qrcode:
    $ref: "./paths/links-shortCode-qrcode.yaml"
components:
  schemas:
    CreateLinkRequest:
      $ref: "./schemas/CreateLinkRequest.yaml"
    CreateLinkResponse:
      $ref: "./schemas/CreateLinkResponse.yaml"
    ErrorResponse:
      $ref: "./schemas/ErrorResponse.yaml"
  parameters:
    ShortCodePathParam:
      in: path
      name: shortCode
      description: Short Code to be fetched
      required: true
      schema:
        type: string
        minLength: 3
