spring:
  application:
    name: url-service

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

server:
  port: 5233

logging:
  level:
    io.urlshortener: INFO

aws:
  region: us-west-2
  credential:
    access-key: test
    secret-key: test
  dynamodb:
    endpoint-override: http://localhost:4566
    tables:
      links-table: "Links"

url-shortener:
  base-url: http://shortify.com/
  short-code-length: 7
